from linerate.domain import ConductorParameters

conductor_565 = ConductorParameters(
    name="565-AL1/72-ST1A",
    aluminium_area=565,
    total_area=636.6,
    weight_per_unit_length=14.9,
    rated_tensile_strength=174.14,
    horizontal_component_of_tension=34.83,
    conductor_temperature_1=20,
    conductor_temperature_2=80,
    final_modulus_of_elasticity_of_conductor=76000,
    initial_modulus_of_elasticity_of_conductor=61000,
    nominal_diameter=32.8,
    conductor_diameter=32.9,
    number_of_wires=54,
    outer_layer_strand_diameter=3.52,
    steel_core_diameter=11,
    sectional_area_of_steel_core=71.6,
    linear_mass=2.543,
    rated_strength=17414,
    coefficient_of_linear_expansion=0.000023,
    resistance_per_km=0.0500,
    resistance_per_km_at_high_temperature=0.0621,
    solar_absorptivity=0.9,
    emissivity=0.9,
    specific_heat_capacity_of_steel_at_20c=481,
    specific_heat_capacity_of_aluminum_at_20c=897,
    temperature_coefficient_of_steel_specific_heat_capacity=0.001,
    temperature_coefficient_of_aluminum_specific_heat_capacity=0.0038,
    weight_per_unit_length_aluminium=1.9254,
    weight_per_unit_length_steel=0.6176,
    constant_magnetic_effect = 1,
    current_density_proportional_magnetic_effect = 0,
    max_magnetic_core_relative_resistance_increase = 1,
)

